name: gameverse
description: "Like Steam, this platform is a place to buy/download games, sell/develop games, and more. It is a platform for gamers and game developers alike."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.5

  # Networking
  http: ^1.4.0

  # Authorization
  supabase_flutter: ^2.9.1
  url_launcher: ^6.3.1

  # Config
  flutter_dotenv: ^5.2.1
  app_links: ^6.4.0

  # Model generation
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  freezed: ^3.0.6

  # Routing
  go_router: ^16.0.0

  # Customize size application
  bitsdojo_window: ^0.1.6

  # Load SVG image
  flutter_svg: ^2.2.0

  # Webview inside app
  webview_flutter: ^4.13.0

  # Secured Storage
  flutter_secure_storage: ^9.2.4

  # Security
  crypto: ^3.0.6

  # Picking files from file explorer
  file_picker: ^10.2.2

  # Path operations
  path: ^1.9.1

  # A http networking package, supports Request cancelation, File uploading/downloading
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.2
  json_serializable: ^6.9.5
  msix: ^3.16.9
  win32: ^5.14.0
  ffi: ^2.1.4


flutter:
  uses-material-design: true

  fonts:
    - family: Play
      fonts:
        - asset: assets/fonts/Play-Regular.ttf
        - asset: assets/fonts/Play-Bold.ttf
          weight: 700

  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/
    - .env

msix_config:
  display_name: gameverse
  msix_version: 1.0.0.0
  protocol_activation: https, gameverse # Add the protocol activation for the app
  # app_uri_handler_hosts: www.example.com, example.com # Add the app uri handler hosts
